name: spirit_within_flutter
description: A new Flutter application for SpiritWithin

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  share: ^2.0.1
  path_provider: ^2.0.1
  image_picker: ^0.7.4
  http: ^0.13.1
  country_list_pick: ^1.0.1+4
  launch_review: ^3.0.1
  permission_handler: ^6.1.1
  contacts_service: ^0.4.6
  flutter_slidable: ^0.5.7
  pin_code_fields: ^7.0.0
  shared_preferences: ^2.0.5
  zefyr:
    git:
      url: https://github.com/SahilLimbe/zefyr.git
      path: packages/zefyr
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Rasa
      fonts:
        - asset: assets/fonts/Rasa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rasa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rasa-Light.ttf
          weight: 300
        - asset: assets/fonts/Rasa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rasa-SemiBold.ttf
          weight: 600

    - family: SourceSerifPro
      fonts:
        - asset: assets/fonts/SourceSerifPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSerifPro-Black.ttf
          weight: 900
        - asset: assets/fonts/SourceSerifPro-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/SourceSerifPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSerifPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SourceSerifPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceSerifPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/SourceSerifPro-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SourceSerifPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSerifPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SourceSerifPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSerifPro-SemiBoldItalic.ttf
          weight: 600
          style: italic

    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSansPro-Black.ttf
          weight: 900
        - asset: assets/fonts/SourceSansPro-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSansPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/SourceSansPro-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-SemiBoldItalic.ttf
          weight: 600
          style: italic


